name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0 # Quoted, to avoid YAML float 3.0 interplated to "3"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # Run "bundle install", and cache the result automatically.
      - name: Run test
        run: bundle exec rake